/**
 * workflowTemplates.js — Tool-specific GitHub Actions workflow generators
 *
 * Generates optimized `.github/workflows/deployguard.yml` content tailored
 * to each supported build tool. Each template:
 *   - Runs the appropriate build command
 *   - Emits `dist/stats.json` in DeployGuard's expected format
 *   - Tags the artifact with `{ format: "vite" | "nextjs" | "webpack" }` so
 *     the bundle analyser normalises correctly (Phase 2)
 *   - Uploads `dist/` as a `bundle-stats` artifact
 *
 * Allowed format values: "vite" | "nextjs" | "webpack" | "cra"
 */

/**
 * Generate a GitHub Actions workflow YAML for the given build tool.
 *
 * @param {string} buildTool - One of "nextjs" | "vite" | "webpack" | "cra" | "unknown"
 * @returns {string} Complete YAML content ready to commit
 */
function generateWorkflow(buildTool) {
  switch (buildTool) {
    case 'nextjs':
      return nextjsWorkflow();
    case 'webpack':
      return webpackWorkflow();
    case 'cra':
      return craWorkflow();
    case 'vite':
    default:
      return viteWorkflow();
  }
}

// ─── Vite ─────────────────────────────────────────────────────────────────────

function viteWorkflow() {
  return `# DeployGuard Bundle Stats — generated automatically
# Vite projects detected. Do not edit this file manually.
name: DeployGuard Bundle Stats

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Generate DeployGuard stats
        run: |
          node - << 'EOF'
          const fs   = require('fs');
          const path  = require('path');
          const distDir = './dist/assets';
          const files = fs.existsSync(distDir)
            ? fs.readdirSync(distDir).map(f => ({
                name: f,
                size: fs.statSync(path.join(distDir, f)).size,
              }))
            : [];
          fs.mkdirSync('./dist', { recursive: true });
          fs.writeFileSync('./dist/stats.json', JSON.stringify({ format: 'vite', assets: files }, null, 2));
          EOF

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: dist/
          retention-days: 7
`;
}

// ─── Next.js ──────────────────────────────────────────────────────────────────

function nextjsWorkflow() {
  return `# DeployGuard Bundle Stats — generated automatically
# Next.js project detected. Do not edit this file manually.
name: DeployGuard Bundle Stats

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (Next.js)
        run: npm run build

      - name: Generate DeployGuard stats
        run: |
          node - << 'EOF'
          const fs   = require('fs');
          const path = require('path');
          const nextDir = './.next/static/chunks';
          const files = fs.existsSync(nextDir)
            ? fs.readdirSync(nextDir, { recursive: true }).flatMap(f => {
                const full = path.join(nextDir, f);
                try {
                  const stat = fs.statSync(full);
                  return stat.isFile() ? [{ name: f, size: stat.size }] : [];
                } catch { return []; }
              })
            : [];
          fs.mkdirSync('./dist', { recursive: true });
          fs.writeFileSync('./dist/stats.json', JSON.stringify({ format: 'nextjs', assets: files }, null, 2));
          EOF

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: dist/
          retention-days: 7
`;
}

// ─── Webpack ──────────────────────────────────────────────────────────────────

function webpackWorkflow() {
  return `# DeployGuard Bundle Stats — generated automatically
# Webpack project detected. Do not edit this file manually.
name: DeployGuard Bundle Stats

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with stats (Webpack)
        run: npx webpack --json > dist/webpack-stats.json 2>/dev/null || npm run build

      - name: Generate DeployGuard stats
        run: |
          node - << 'EOF'
          const fs = require('fs');
          let assets = [];
          if (fs.existsSync('./dist/webpack-stats.json')) {
            try {
              const raw = JSON.parse(fs.readFileSync('./dist/webpack-stats.json', 'utf8'));
              assets = (raw.assets || []).map(a => ({ name: a.name, size: a.size }));
            } catch {}
          }
          fs.mkdirSync('./dist', { recursive: true });
          fs.writeFileSync('./dist/stats.json', JSON.stringify({ format: 'webpack', assets }, null, 2));
          EOF

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: dist/
          retention-days: 7
`;
}

// ─── Create React App ─────────────────────────────────────────────────────────

function craWorkflow() {
  return `# DeployGuard Bundle Stats — generated automatically
# Create React App project detected. Do not edit this file manually.
name: DeployGuard Bundle Stats

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (CRA)
        run: npm run build
        env:
          CI: false

      - name: Generate DeployGuard stats
        run: |
          node - << 'EOF'
          const fs   = require('fs');
          const path = require('path');
          const buildDir = './build/static';
          const files = fs.existsSync(buildDir)
            ? fs.readdirSync(buildDir, { recursive: true }).flatMap(f => {
                const full = path.join(buildDir, f);
                try {
                  const stat = fs.statSync(full);
                  return stat.isFile() ? [{ name: f, size: stat.size }] : [];
                } catch { return []; }
              })
            : [];
          fs.mkdirSync('./dist', { recursive: true });
          fs.writeFileSync('./dist/stats.json', JSON.stringify({ format: 'cra', assets: files }, null, 2));
          EOF

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: dist/
          retention-days: 7
`;
}

module.exports = { generateWorkflow };
